name: Example for minimal setup
on:
  push:
    branches:
      - master

jobs:
  isabelle_mac_os:
    name: Testing Skip Lists
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download isabelle
      run: wget "http://isabelle.in.tum.de/dist/Isabelle2020_macos.tar.gz"
    - name: Untar isabelle
      run: tar -xf "Isabelle2020_macos.tar.gz"
    - name: Build HOL-Library
      run: Isabelle2020.app/Isabelle/bin/isabelle build -d thys/ -b -v Skip_Lists
    - uses: actions/upload-artifact@v2
      with:
        name: skip_list_heaps
        path: ~/.isabelle/heaps
